
#ifndef BASICS_H
#define BASICS_H

/*basic.cool contents generated by running external program embedfile
  Using command "embedfile basics basic.cool", this file created basics.c file containing a char array with the content of
 * basic.cool. This array is used when basic.cool can't be opened at the start of the program. So this acts as a default resource
 */
extern const char basics[];

extern const char ignConstrs[];

#endif
